#include <iostream>
using namespace std;
main(){
float num1;
float num2;
float num3;
float num4;
float num5;
float num6;
float num7;
float num8;
float num9;
float num10;
float num11;
float num12;
float num13;
float num14;
float num15;
float result1;
float result2;
float result3;
float result4;
float result;
cout << "Enter first number: ";
cin >> num1;
cout << "Enter second Number: ";
cin >> num2;
cout << "Enter Third number: ";
cin >> num3;
cout << "Enter Fourth number: ";
cin >> num4;
cout << "Enter Fifth number: ";
cin>> num5;
cout << "Enter six number: ";
cin>> num6;
cout << "Enter seven number: ";
cin>> num7;
cout << "Enter eight number: ";
cin >> num8;
cout << "Enter nine number: ";
cin >> num9;
cout << "Enter ten number: ";
cin >> num10;
cout << "Enter eleven number: ";
cin >> num11;
cout << "Enter twelve number: ";
cin >> num12;
cout << "Enter thirteen number: ";
cin >> num13;
cout << "Enter forteen number: ";
cin >> num14;
cout << "Enter fifteen number: ";
cin>> num15;

result1=  (num1+num2+num3+num4+num5);
result2=  (num6*num7*num8*num9*num10);
result3= result1 +result2;
result4= num11-num12-num13-num14-num15;
result= result3 - result4;
cout<< "Result is: "<< result; 

}